name: Generate F-Droid repo

on:
  push:
    branches: [ master ]
  workflow_dispatch:
  schedule:
  - cron: "45 2 * * *"

jobs:
  apps:
    name: "Generate repo from apps listing"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v2

      - name: Create basic directory structure
        run: mkdir -p fdroid/repo

      - name: Restore correct mtime
        run: |
          sudo apt install git-restore-mtime 
          git restore-mtime

      - name: Install F-Droid server software
        run: |
         sudo add-apt-repository ppa:fdroid/fdroidserver
         sudo apt-get update
         sudo apt-get install fdroidserver

      - name: Set up repo secrets
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 -d - > fdroid/keystore.p12
          echo "${{ secrets.CONFIG_YML }}" | base64 -d - > fdroid/config.yml

      - uses: actions/setup-go@v2
        name: Set up Go
        with:
          go-version: '^1.17.0' 
        
      - name: Run update script
        run: bash update.sh 2>&1
        env:
          GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Prepare GHPages
        run: |
                mkdir public
                mv -v ./fdroid/* public/
                cp index.html public/
                cp index.html public/repo/
                cp index.html public/404.html
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
            path: public
    
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
